# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 17:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cart_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=10, size=None),
            preserve_default=False,
        ),
    ]
