# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_images', models.TextField(blank=True, null=True)),
                ('product_rating', models.FloatField(blank=True, null=True)),
                ('product_price', models.FloatField()),
                ('product_vendor_id', models.IntegerField(blank=True, null=True)),
                ('product_features', models.TextField(blank=True, null=True)),
                ('product_detail', models.TextField(blank=True, null=True)),
                ('product_reviews', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
